# Generated by Django 3.1.1 on 2021-05-24 14:48

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_auto_20210524_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='baner',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/baners/', verbose_name='Casino Baner'),
        ),
    ]
