# Generated by Django 3.1.1 on 2021-05-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0009_auto_20210526_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='name_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_br',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_cs',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_da',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_gb',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_no',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_nz',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_ro',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_sk',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='name_us',
        ),
    ]
