# Generated by Django 3.1.1 on 2021-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0010_auto_20210526_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='link_au',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_br',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ca',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_cs',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_da',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_de',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_en',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_es',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_fi',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_gb',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_hu',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_it',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_nl',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_no',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_nz',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_pl',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ro',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_sk',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_sv',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_us',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
    ]
