# Generated by Django 3.1.1 on 2021-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0013_auto_20210607_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='adv1_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_be',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_bg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_ie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_in',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_jp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_my',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_ph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_sg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_th',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_za',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_be',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_bg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_ie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_in',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_jp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_my',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_ph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_sg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_th',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_za',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_be',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_bg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_ie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_in',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_jp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_my',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_ph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_sg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_th',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_za',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_at',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_be',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_bg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ie',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_in',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ind',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_jp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_my',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_sg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_th',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_tr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_za',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_at',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_be',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_bg',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ch',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_fr',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ie',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_in',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ind',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_jp',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_my',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_ph',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_sg',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_th',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_tr',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_za',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_at',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_bg',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ch',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ie',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_in',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_jp',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_my',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ph',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_sg',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_za',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_at',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_be',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_bg',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ch',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_fr',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ie',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_in',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ind',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_jp',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_my',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ph',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_sg',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_th',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_za',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
    ]
