# Generated by Django 3.1.1 on 2021-06-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0018_auto_20210607_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='promocode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Promo Code'),
        ),
    ]
