# Generated by Django 3.1.1 on 2021-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0025_auto_20210630_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='max_bet',
            field=models.FloatField(blank=True, null=True, verbose_name='Max bet'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='max_cashout',
            field=models.FloatField(blank=True, null=True, verbose_name='Max cashout'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='min_dep',
            field=models.FloatField(blank=True, null=True, verbose_name='Min deposit'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='wagering',
            field=models.FloatField(blank=True, null=True, verbose_name='Wagering'),
        ),
    ]
