# Generated by Django 3.1.1 on 2021-06-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0026_auto_20210630_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='bonus',
            field=models.ManyToManyField(blank=True, related_name='bonuses', to='casinos.Bonus'),
        ),
    ]
