# Generated by Django 3.1.1 on 2021-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0027_auto_20210630_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='svg_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='svg name in sprite'),
        ),
    ]
