# Generated by Django 3.1.1 on 2021-07-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0028_game_svg_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='wagering',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wagering'),
        ),
    ]
