# Generated by Django 3.1.1 on 2021-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bonus_score',
            field=models.IntegerField(default=100, verbose_name='Bonus Score'),
        ),
        migrations.AddField(
            model_name='casino',
            name='games_score',
            field=models.IntegerField(default=100, verbose_name='Games Score'),
        ),
        migrations.AddField(
            model_name='casino',
            name='payout_score',
            field=models.IntegerField(default=100, verbose_name='Payout Score'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='trust_score',
            field=models.IntegerField(default=100, verbose_name='Quality Score'),
        ),
    ]
