# Generated by Django 3.1.1 on 2021-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0007_casino_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
