# Generated by Django 3.1.1 on 2021-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0008_casino_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='position_en',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_br',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_ca',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_cs',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_da',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_gb',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_no',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_nz',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_ro',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_sk',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_us',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_au',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_br',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_ca',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_cs',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_da',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_de',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_fi',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_gb',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_hu',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_it',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_nl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_no',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_nz',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_pl',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_ro',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_sk',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_sv',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='position_us',
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv1_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv2_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv3_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='bonus_link',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Bonus Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link',
            field=models.CharField(default='#', max_length=180, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_au',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_br',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_ca',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_cs',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_da',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_de',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_gb',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_it',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_nz',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_pl',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_ro',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_sk',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='name_us',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_es',
            field=models.ManyToManyField(blank=True, related_name='pays_es', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='reg_link',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Reg Link'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_au',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_br',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_da',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_fi',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_gb',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_hu',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_nz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_pl',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_sk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_sv',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='header_us',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_au',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_br',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ca',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_cs',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_da',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_de',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_es',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_fi',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_gb',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_hu',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_it',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_nl',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_no',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_nz',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_pl',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_ro',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_sk',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_sv',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='countries',
            name='text_us',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_br',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_ca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_cs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_da',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_gb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_nz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_ro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_sk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv1_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo1 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_br',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_ca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_cs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_da',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_gb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_nz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_ro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_sk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv2_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo2 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_br',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_ca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_cs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_da',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_gb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_nz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_ro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_sk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='adv3_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo3 EN'),
        ),
    ]
