# Generated by Django 3.1.1 on 2021-05-28 12:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0011_auto_20210528_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='baner',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='upload/img/promo/', verbose_name='Casino Baner'),
        ),
    ]
