# Generated by Django 3.1.1 on 2021-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0012_auto_20210528_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='adv4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_au',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_br',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_cs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_da',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_de',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_fi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_gb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_hu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_nl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_nz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_pl',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_ro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_sk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_sv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='adv4_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Promo4 EN'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_at',
            field=models.ManyToManyField(blank=True, related_name='pays_at', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_be',
            field=models.ManyToManyField(blank=True, related_name='pays_be', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_bg',
            field=models.ManyToManyField(blank=True, related_name='pays_bg', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_ch',
            field=models.ManyToManyField(blank=True, related_name='pays_ch', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_fr',
            field=models.ManyToManyField(blank=True, related_name='pays_fr', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_id',
            field=models.ManyToManyField(blank=True, related_name='pays_id', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_ie',
            field=models.ManyToManyField(blank=True, related_name='pays_ie', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_in',
            field=models.ManyToManyField(blank=True, related_name='pays_in', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_jp',
            field=models.ManyToManyField(blank=True, related_name='pays_jp', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_my',
            field=models.ManyToManyField(blank=True, related_name='pays_my', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_ph',
            field=models.ManyToManyField(blank=True, related_name='pays_ph', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_sg',
            field=models.ManyToManyField(blank=True, related_name='pays_sg', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_th',
            field=models.ManyToManyField(blank=True, related_name='pays_th', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_tr',
            field=models.ManyToManyField(blank=True, related_name='pays_tr', to='casinos.Payment'),
        ),
        migrations.AddField(
            model_name='casino',
            name='pay_za',
            field=models.ManyToManyField(blank=True, related_name='pays_za', to='casinos.Payment'),
        ),
    ]
