# Generated by Django 3.1.1 on 2021-07-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0029_auto_20210701_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='details_text',
        ),
        migrations.AddField(
            model_name='casino',
            name='details_text_hidden',
            field=models.TextField(blank=True, null=True, verbose_name='Details text hidden'),
        ),
        migrations.AddField(
            model_name='casino',
            name='details_text_visible',
            field=models.TextField(blank=True, null=True, verbose_name='Details text visible'),
        ),
    ]
