# Generated by Django 3.1.1 on 2021-07-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0030_auto_20210701_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='baner',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='screen',
        ),
    ]
