# Generated by Django 3.1.1 on 2021-07-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0032_auto_20210708_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paycountry',
            options={'verbose_name': 'Pay Country', 'verbose_name_plural': 'Pay Countries'},
        ),
    ]
