"""
Django settings for land project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4(b4-5_a&wnuc@6k7w(3&jnnb2c4f77_cq_v&=ltcbky$couh@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.sites',
    'casinos',
    'easy_thumbnails',
    'modeltranslation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'land-dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'land-dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en'
 
LANGUAGES = (
  ('en', 'EN'),
  ('pl', 'PL'),
  ('de', 'DE'),
  ('cs', 'CS'),
  ('sk', 'SK'),
  ('it', 'IT'),
  ('hu', 'HU'),
  ('ro', 'RO'),
  ('sv', 'SV'),
  ('nl', 'NL'),
  ('au', 'AU'),
  ('ca', 'CA'),
  ('us', 'US'),
  ('gb', 'UK'),
  ('br', 'BR'),
  ('fi', 'FI'),
  ('nz', 'NZ'),
  ('no', 'NO'),
  ('da', 'DA'),
  ('es', 'ES'),
  ('be', 'BE'),
  ('bg', 'BG'),
  ('fr', 'FR'),
  ('id', 'ID'),
  ('my', 'MY'),
  ('th', 'TH'),
  ('tr', 'TR'),
  ('at', 'AT'),
  ('ch', 'CH'),
  ('ie', 'IE'),
  ('in', 'IN'),
  ('jp', 'JP'),
  ('ph', 'PH'),
  ('sg', 'SG'),
  ('za', 'ZA'),
)
MODELTRANSLATION_LANGUAGES = ('en', 'pl', 'de', 'cs', 'sk', 'it', 'hu', 'ro', 'sv', 'nl', 'au', 'ca', 'us', 'gb', 'br', 'fi', 'nz', 'no', 'da', 'es', 'be', 'bg', 'fr', 'id', 'my', 'th', 'tr', 'at', 'ch', 'ie', 'in', 'jp', 'ph', 'sg', 'za')

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'

MODELTRANSLATION_TRANSLATION_REGISTRY = 'casinos.translation'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
	os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

THUMBNAIL_ALIASES = {
    '': {
        'site_logo': {'size': (0, 50), 'crop': False},
        'site_promo': {'size': (1120, 290), 'crop': True},
        'logo': {'size': (200, 0), 'crop': False},
        'screen': {'size': (712, 0), 'crop': False},
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 
MEDIA_URL = '/media/'
 
 
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
 
STATIC_URL = '/static/'
